#+LATEX_CLASS: ltxdockit
#+TITLE:Theorical Minimum
#+AUTHOR:于要杰
#+STARTUP:hidestars
#+OPTIONS: H:4 toc:2 ^:{}
#+EMAIL:yuyaojie1234@gmail.com
* 运动
  #+BEGIN_QUOTE
  Lenny抱怨说:"George, 这种跳跃的方式让我感到紧张.我们的时间真是以这种阶越的方式运行吗? 我希望一切可以更流畅一些."

  George想了一会儿,把黑板擦干净,说道,"好的,Lenny, 今天让我们来学习那些连续变化的系统."
  #+END_QUOTE
** 数学序曲:微分学
   在本书中,我们主要研究变量是如何随着时间变化. 经典力学绝大部分的内容都是处理物体随时间光滑变化的情形-既数学上的连续变化这一术语. 不像我们第一节中那样的随时间离散变化系统,此时系统的动力法则是连续的随时间从系统一个状态过渡到另一个状态. 因此,我们将对以时间 $t$ 为自变量的函数感兴趣.
   对于连续的变化,在数学上,我们将使用为微积分这一工具. 微积分是极限的运算,因此有必要首先理解极限这一概念. 假设我们有一个数列, $l_{1},l_{2},l_{3},...$ ,这一数列越来越逼近一个值 $L$. 例如,数列 0.9, 0.99 ,0.999, 0.9999, .... 这个数列的极限是1. 数列没有一项为1,但随着n的增长,数列的项越来越接近1. 我们一一下方式来表示这种情况.
   
   $$lim_{i->\infty}l_{i}=L$$

   既L是 $l_{i}$ 随着 $i$ 趋于无穷时的极限.

   这一思想同样可以应用于函数. 假设我们有一个函数- $f(t)$ , 我们想描述当 $t$ 不断趋近某一个值时,函数值的变化情况. 如果当 $t$ 趋近 $a$ 时, $f(t)$ 任意趋近 $L$, 那我们就说当 $t$ 趋近于 $a$ 时 $f(t)$ 的极限是 $L$ .记作如下.

   $$lim_{t->a}f(t) =L.$$

   让 $f(t)$ 是变量 $t$ 的函数,既 $t$ 变化时, $f(t)$ 相应变化. 微分处理的时这类函数的变化率的问题. 微分的思想是在 $f(t)$ 的某个时刻,改变一点点的时间来观察 $f$ 是如何相对于 $t$ 变化. 我们一希腊字母 $\delta$ 表示这种个变化. 让我们把时间 $t$ 上的改变称为 $\delta t$ (这里不是 $\delta X t$ ,而是表示 $t$ 上的微小变化). 在 $\delta t$ 这一时间片中, $f$ 从 $f(t)$ 变化到 $f(t + \delta t)$. $f$ 的变化,记作 $\delta f$ , 其含义如下,

   $$\delta f = f(t+ \delta t)-f(t)$$

   为了精确地定义 $t$ 时刻的变化率, 我们必须令 $\delta t$ 趋于0. 当然,当我们将 $\delta t$ 趋于0 的时候, $\delta f$ 也会趋于0, 但是如果我们令 $\delta f$ 除以 $\delta t$, 这个比例将趋于一个极限. 这个极限是 $f(t)$ 关于 $t$ 的导数,

   $$\frac{d f(t)}{dt}=lim_{\delta t -> 0}\frac{\delta f}{\delta t}=lim_{\delta t->0}\frac{f(t+\delta t) - f(t)}{\delta t}$$

   一个严谨的数学家更喜欢将 $$\frac{d f(t)}{d t}$$ 看作是两个微分的比值,但我们这里会保证你不会出现错误.

   让我们来计算一些导数. 首先从 $t$ 的指数函数开始. 特别地, 我们将方法应用到 $f(t) = t^{2} $ 这一个函数. 我们将通过定义$f(t+\delta t)$应用上面的公式:

   $$f(t + \delta t) = (t + \delta t)^{2}.$$

   我们可以将$(t + \delta t)^{2} 因式分解.得到:

   $$f(t + \delta t) = t^{2} + 2t \delta t + \delta t^{2}$$

   提取出$f(t)$:

   $$f(t + \delta t)-f(t) = t^{2} + 2t \delta t + \delta t^{2} - t^{2}$$
   $$=2t\delta t + \delta t^{2}$$

   下一步是除以 $\delta t$:

   $$\frac{f(t+\delta t)-f(t)}{\delta t}=\frac{2t \delta t + \delta t^{2}}{\delta t}$$
   $$ 2t +\delta t$$

   现在,取 $\delta t \to 0$ 的极限变的容易. 第一项步依赖 $\delta t$ , 但是第二项会趋于零并消失. 这里需要记住: 高于 $\delta t$ 的项在计算微分的时候会被忽略. 因此,

   $$\lim_{\delta t \to 0}\frac{f(t+\delta t)-f(t)}{\delta t}=2t$$

   $t^{2}$ 的导数是

   $$\frac{d(t^{2})}{dt}=2 t$$

   现在让我们考虑更一般的幂函数, $f(t) = t^{n}$. 为了计算它的导数, 我们首先要计算 $f(t+\delta t) =(t + \delta t)^{2}$. 可以用二项式定理来解决. 给定两个数, $a$ 和 $b$, 我们可以计算 $(a + b)^{n}. 二项式 定理如下:

   $$(a + b)^{n} = a^{n} + n a^{n -1} b + \frac{n (n-1)}{2} a^{n-2} b^{2}+ \frac{n(n-1)(n-2)}{3} a^{n-3} b^{3}+...+b^{n}$$

   这个表达式有多长? 如果 $n$ 是整数的话, 最终会有 $n+1$ 项. 但事实上, $n$ 可以是任意的实数或复数. 如果 $n$ 不是一个整数, 这个表达式不会结束,它是一个无穷级数. 幸运地是,对于我们的目的,只有头两项是重要的.

   为了计算 $(t+\delta t)^{n}$, 我们所做的是将 $a=t$ 和 $b=\delta t$ ,得到,

   $$f(t + \delta t) = (t + \delta t)^{n} =t^{n} + nt^{n-1} \delta t + .... $$
   

   所有以点点表示的项在极限中趋于零,因此将其忽略.

   现在提取 $f(t)$ 或 ($t^{n}$,

   $$\delta f = f(t+\delta t) - f(t) = t^{n} + n t^{n-1} \delta t + \frac{n(n-1)}{2}t^{n-2}\delta t^{2} + ... -t^{n}$$
   $$nt^{n-1}\delta t + \frac{n(n-1)}{2}t^{n-2}\delta t^{2} + ....$$
   
   除以 $\delta t$ ,
   $$\frac{\delta f}{\delta t} = n t^{n-1} + \frac{n(n-1)}{2}t^{n-2}\delta t + ....$$
   并且使 \delta t -> 0. 导数为

   $$\frac{d(t^{n}}{dt}=nt^{n-1}$$

   重要的一点是,这个关系对于n不是整数仍然成立,n可以是任何实数或复数.

   这里给出一些该导数的特例: 如果 $n=0$ , 那么 $f(t)$ 只是一个数 1. 导数为0-这也是对与任何不会改变函数的情况. 如果 $n=1$ , 那么 $f(t) = t$  并且导数为1-当你对其自身求导时往往如此. 这里是一些幂函数的导数.

   $$\frac{d(t^{2})}{dt }= 2t $$
   $$\frac{d(t^{3})}{dt }= 3t^{2}$$
   $$\frac{d(t^{4})}{dt }= 4t^{3}$$
   $$\frac{d(t^{n})}{dt }= (n) t^{n-1}$$

   下面是一些将来经常会用到的一些导数:

   $$\frac{d sin t}{dt}= cos t $$
   $$\frac{d cos t}{dt}= -sin t $$
   $$\frac{d e^{t}}{dt}= e^{t} $$
   $$\frac{d(log t )}{dt}= \frac{1}{t}.$$
    
   我们给第三个公式一些注解. 当 $t$ 是整数时, $e^{t}$ 的含义是十分清晰的. 比如 $e^{3} = exexe$. 但当 $n$ 不是整数的时候,其含义不是非常的明显. 基本上, $e^{t}$ 的定义是其导数仍是其本身. 因此第三个公式也是一个定义式.

   有一些有用的法则来记忆这些导数. 你也可以把他们作为一些具有挑战的联系来做. 第一个事实是,一个常数的导数为0. 导数是变量的变化率,一个常数是不会变化的,因此其导数恒为零.

   $$\frac{dc}{dt}=0.$$

   一个常数乘以一个函数的导数是这个常数乘以该函数的导数.

   $$\frac{cf}{dt}=c \frac{df}{dt}. $$

   假设我们有两个函数, $f(t)$ 和 $g(t)$ . 他们的和是一个函数并且它们的和的导数如下,

   $$\frac{d(f+g)}{dt}=\frac{d(f)}{dt}+\frac{d(g)}{dt}. $$

   这个项叫做和的规则.

   它们的积是另外的一个函数,它的导数是,

   $$\frac{d(fg)}{dt}=f(t) \frac{d(g)}{dt}+g(t)\frac{d(f)}{dt}. $$

   这个叫做乘积律.

   下一步,假设 $g(t)$ 是 $t$ 的函数, $f(g)$ 是 $g$ 的一个函数. 这使得 $f$ 是 $t$ 的一个隐函数. 如果你想知道某个 $t$ 时的 $f$ ,那你首先计算 $g(t)4 . 知道 $g$ 后,你就计算 $f(g)$ . 计算 $f$ 关于 $t$ 的导数:

   $$\frac{df}{dt}=\frac{df}{dg}\frac{dg}{dt}. $$

   
   这条称为链式法则. 如果导数是分数的话该法则成立是显然的,这种情况下,分子分母上的 $dg$ 将相互抵消. 使用链式法则时候要记住,需要构造一个中间函数, $g(t)$ ,使得 $f(t)$ 简化为 $f(g)$ . 例如,

   $$f(t) = ln t^{3} $$

   我们需要找到 $\frac{d f}{d t}$, 此是式中的 $t^{3}$ 将会是一个问题. 因此,我们首先构造中间函数 $g=t^{3}$ , 因此我们将有 $f(g) = lng$. 此时我们可以使用链式法则.

$$\frac{df}{dt}=\frac{df}{dg}\frac{dg}{dt}. $$

   我们可以用微分公式 $\frac{d f}{d g}= \frac{1}{g}$ 和 $\frac{g}{d t}=3 t^{2}$,因此,

   $$\frac{df}{dt} = \frac{3t^{2}}{g}. $$

   我们可以替换 $g=t^{3}$, 获得,

   $$\frac{df}{dt} = \frac{3 t^{3}}{t^{3}}=\frac{3}{t}. $$

   这是我们如何使用链式法则.
   
   使用这些法则,你可以计算许多导数. 这基本上就是所有的微分学.

   
   

   

   